[package]
name = "common"
version = "0.0.0"
authors = ["Yun Yeo <YunSuk-Yeo@users.noreply.github.com>"]
edition = "2018"
description = "Mocks to use for testing Terra Contracts"
repository = "https://github.com/terra-project/luna-vesting/tree/master/packages/common"
license = "Apache-2.0"
readme = "README.md"

exclude = [
  # Those files are cosmwasm-opt artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.9.0"
cosmwasm-std = { version = "0.16.0", features = ["stargate","staking"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
